apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp
data:
  key: value

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: argoproj/rollouts-demo:blue
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - name: myapp
              mountPath: /config
      volumes:
        - name: myapp
          configMap:
            name: myapp
