apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-2
spec:
  components:
    - name: wf-poc-app-2
      type: webservice
      properties:
        image: oamdev/helloworld-python:v1
        env:
          - name: "TARGET"
            value: "ArgoCD"
        port: 8080
  policies:
    - name: topology-local
      type: topology
      properties:
        clusters: ["local"]
    - name: topology-dev
      type: topology
      properties:
        clusters: ["dev"]
        namespace: test
  workflow:
    steps:
      - type: deploy
        name: deploy-local
        properties:
          policies: ["topology-local"]
      - type: deploy
        name: deploy-dev
        properties:
          # require manual approval before running this step
          auto: false
          policies: ["topology-dev"]
